use assert_cmd::Command;
use predicates::prelude::*;

fn testdata(name: &str) -> String {
    format!("{}/../../testdata/{name}", env!("CARGO_MANIFEST_DIR"))
}

fn dps() -> Command {
    let mut cmd = Command::cargo_bin("docray").unwrap();
    cmd.env(
        "DOCRAY_PDFIUM_DIR",
        format!("{}/../../.pdfium/lib", env!("CARGO_MANIFEST_DIR")),
    );
    cmd.timeout(std::time::Duration::from_secs(30));
    cmd
}

// Deviation from the brief: the encrypted fixture lives under testdata/encrypted/
// rather than directly at testdata/encrypted.pdf. The golden harness
// (crates/docray-pdf/tests/golden.rs) globs every *.pdf directly inside testdata/
// and calls PdfExtractor::extract on it unconditionally; extracting an
// encrypted PDF fails, which would break that harness. Putting it in a
// subdirectory keeps it out of that top-level glob.
#[test]
fn encrypted_pdf_exits_3() {
    dps()
        .arg("extract")
        .arg(testdata("encrypted/encrypted.pdf"))
        .assert()
        .code(3)
        .stderr(predicate::str::contains("\"encrypted_pdf\""));
}

#[test]
fn empty_file_exits_2() {
    dps()
        .arg("extract")
        .arg(testdata("malformed/empty.pdf"))
        .assert()
        .code(2)
        .stderr(predicate::str::contains("\"unsupported_format\""));
}

#[test]
fn truncated_pdf_never_panics() {
    // Either recovers with warnings (exit 0) or fails structurally (exit 4) —
    // both fine; a panic/abort (101/134) is not.
    let assert = dps()
        .arg("extract")
        .arg(testdata("malformed/truncated.pdf"))
        .assert();
    let code = assert.get_output().status.code().unwrap_or(-1);
    assert!(code == 0 || code == 4, "unexpected exit code {code}");
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(!stderr.contains("panicked"), "extractor panicked: {stderr}");
}

#[test]
fn garbage_bytes_exit_2() {
    dps()
        .arg("extract")
        .arg(testdata("malformed/garbage.bin"))
        .assert()
        .code(2)
        .stderr(predicate::str::contains("\"unsupported_format\""));
}

#[test]
fn malformed_pptx_corpus_is_structured_and_never_panics() {
    for (name, code, error_code) in [
        ("zip-bomb.pptx", 4, "parse_failure"),
        ("path-traversal.pptx", 4, "parse_failure"),
        ("truncated.pptx", 4, "parse_failure"),
        ("not-pptx.zip", 2, "unsupported_format"),
        ("legacy-office.cfb", 2, "unsupported_format"),
    ] {
        dps()
            .arg("extract")
            .arg(testdata(&format!("malformed/{name}")))
            .args(["--granularity", "element"])
            .assert()
            .code(code)
            .stderr(predicate::str::contains(format!("\"{error_code}\"")))
            .stderr(predicate::str::contains("panicked").not());
    }
}

#[test]
fn xxe_fixtures_extract_without_entity_expansion() {
    for name in ["xxe.pptx", "external-entity.pptx"] {
        dps()
            .arg("extract")
            .arg(testdata(&format!("malformed/{name}")))
            .args(["--granularity", "element"])
            .assert()
            .success()
            .stdout(predicate::str::contains("&xxe;"))
            .stdout(predicate::str::contains("EXPANSION_MUST_NOT_APPEAR").not());
    }
}

// corrupt-page.pdf (generated by gen_fixtures.rs) is a structurally valid
// 3-page PDF whose page 2 content stream bytes were overwritten with 'X'
// after saving. The container (xref, page tree) still parses, so extraction
// succeeds; only page 2's drawable content is unreadable.
//
// Verified behavior: pdfium's content-stream parser recovers *silently* here
// — no warning is produced for page 2, it just yields zero objects for that
// page while pages 1 and 3 (untouched) keep their content. This test asserts
// that actual behavior (empty page 2) but also accepts a page-2 warning,
// in case a future pdfium/pdfium-render upgrade starts surfacing one.
#[test]
fn corrupt_page_content_stream_extracts_with_empty_page_two() {
    let assert = dps()
        .arg("extract")
        .arg(testdata("malformed/corrupt-page.pdf"))
        .assert()
        .success();
    let stdout = String::from_utf8_lossy(&assert.get_output().stdout).into_owned();
    let json: serde_json::Value = serde_json::from_str(&stdout).unwrap();

    assert_eq!(json["document"]["page_count"], 3);
    let pages = json["pages"].as_array().unwrap();
    assert_eq!(pages.len(), 3);

    let elements_of = |i: usize| pages[i]["elements"].as_array().unwrap().len();
    let warnings = json["warnings"].as_array().unwrap();
    let warned_about_page2 = warnings
        .iter()
        .any(|w| w.as_str().unwrap_or("").contains("page 2"));

    assert!(
        elements_of(1) == 0 || warned_about_page2,
        "expected page 2 empty or warned-about; got {} elements, warnings {warnings:?}",
        elements_of(1)
    );
    assert!(elements_of(0) > 0, "page 1 should still have its content");
    assert!(elements_of(2) > 0, "page 3 should still have its content");
}
